--<ScriptOptions statementTerminator=";"/>

CREATE TABLE BCITEMLST (
		BCMSGID DECIMAL(9 , 0) NOT NULL,
		BCITEMID DECIMAL(9 , 0) NOT NULL,
		AMOUNT DECIMAL(15 , 2) NOT NULL,
		ITDUEDAT DECIMAL(8 , 0) NOT NULL,
		VENDORID CHAR(50) NOT NULL,
		FUND CHAR(20) NOT NULL,
		YEARBS CHAR(20) NOT NULL,
		FUNCAREA CHAR(20) NOT NULL,
		ACTIVITY CHAR(20) NOT NULL,
		BUDUSERBS CHAR(50) NOT NULL,
		CODE CHAR(50) NOT NULL,
		YEARCI CHAR(20) NOT NULL,
		DESCRT CHAR(120) NOT NULL,
		TYPE CHAR(20),
		REFDOCHEAD DECIMAL(9 , 0),
		REFITEMNUM CHAR(20),
		LOCATIONBC CHAR(50) NOT NULL,
		USER CHAR(10) NOT NULL,
		DATETIME DECIMAL(8 , 0) NOT NULL
	);

CREATE UNIQUE INDEX BCITEMLST ON BCITEMLST (BCMSGID ASC, BCITEMID ASC);

ALTER TABLE BCITEMLST ADD CONSTRAINT Q_DRRH_BCITEMLST_REFDOCHEAD_00001 FOREIGN KEY (REFDOCHEAD)
	REFERENCES DOCHEAD (BUFMISDOC)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

ALTER TABLE BCITEMLST ADD CONSTRAINT Q_DRRH_BCITEMLST_BCMSGID_00002 FOREIGN KEY (BCMSGID)
	REFERENCES BUDCOMMSG (BCMSGID)
	ON DELETE RESTRICT
	ON UPDATE RESTRICT;

