package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-20T14:40:23.855+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", name = "BankManagementInterface")
@XmlSeeAlso({budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ObjectFactory.class, ObjectFactory.class, budgetuserlibrary.gw.fmis.ibm.hr.messages.ObjectFactory.class})
public interface BankManagementInterface {

    @WebResult(name = "bankResponseMsg", targetNamespace = "")
    @RequestWrapper(localName = "retrieveBank", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.RetrieveBank")
    @WebMethod
    @ResponseWrapper(localName = "retrieveBankResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.RetrieveBankResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.BankResponseMsg retrieveBank(
        @WebParam(name = "bankRetrieveRequestMsg", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.BankRetrieveRequestMsg bankRetrieveRequestMsg
    );

    @WebResult(name = "bankResponseMsg", targetNamespace = "")
    @RequestWrapper(localName = "changeBank", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.ChangeBank")
    @WebMethod
    @ResponseWrapper(localName = "changeBankResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.ChangeBankResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.BankResponseMsg changeBank(
        @WebParam(name = "bankChangeRequestMsg", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.BankChangeRequestMsg bankChangeRequestMsg
    );

    @WebResult(name = "bankResponseMsg", targetNamespace = "")
    @RequestWrapper(localName = "createBank", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.CreateBank")
    @WebMethod
    @ResponseWrapper(localName = "createBankResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.CreateBankResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.BankResponseMsg createBank(
        @WebParam(name = "bankCreationRequestMsg", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.BankCreationRequestMsg bankCreationRequestMsg
    );
}
