package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.binding;

import hr.infomare.drrh.pomocni.Log;
import hr.infomare.drrh.pomocni.PomocnaError;
import hr.infomare.drrh.pomocni.PomocnaWSDL;
import hr.infomare.drrh.postavke.Postavke;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.ReservationManagementService;

/**
 * This class was generated by Apache CXF 2.4.0 2011-10-05T09:15:48.612+02:00
 * Generated source version: 2.4.0
 * 
 */

@WebServiceClient(name = "manageReservationExport_ReservationManagementServiceHttpService",
		wsdlLocation = "http://localhost:8080/Infomare_drrh_web_services/services/manageReservationExport_ReservationManagementServiceHttpPort?wsdl", 
		targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService//Binding")
public class ManageReservationExportReservationManagementServiceHttpService
		extends Service {
	public static String TARGET_NAMESPACE;
	public static String SERVIS;
	public static String PORT;

	public static URL WSDL_LOCATION;
	public static QName SERVICE;
	public static QName manageReservationExportReservationManagementServiceHttpPort;
	static {
		PomocnaWSDL.locirajWebServis(Postavke.WSDL_RESERVATION);
		TARGET_NAMESPACE = PomocnaWSDL.TARGET_NAMESPACE;
		SERVIS = PomocnaWSDL.SERVIS;
		PORT = PomocnaWSDL.PORT;		
		SERVICE = new QName(TARGET_NAMESPACE, SERVIS);
		manageReservationExportReservationManagementServiceHttpPort = new QName(
				TARGET_NAMESPACE, PORT);
		URL url = null;
		try {
			url = new URL(Postavke.WSDL_RESERVATION);
		} catch (MalformedURLException e) {
			Log.loger.severe(PomocnaError.getErrorMessage(e));
		}
		WSDL_LOCATION = url;
	}

	public ManageReservationExportReservationManagementServiceHttpService(
			URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ManageReservationExportReservationManagementServiceHttpService(
			URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ManageReservationExportReservationManagementServiceHttpService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns ReservationManagementService
	 */
	@WebEndpoint(name = "manageReservationExport_ReservationManagementServiceHttpPort")
	public ReservationManagementService getManageReservationExportReservationManagementServiceHttpPort() {
		return super.getPort(
				manageReservationExportReservationManagementServiceHttpPort,
				ReservationManagementService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ReservationManagementService
	 */
	@WebEndpoint(name = "manageReservationExport_ReservationManagementServiceHttpPort")
	public ReservationManagementService getManageReservationExportReservationManagementServiceHttpPort(
			WebServiceFeature... features) {
		return super.getPort(
				manageReservationExportReservationManagementServiceHttpPort,
				ReservationManagementService.class, features);
	}

}
