package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-10-18T09:28:46.677+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", name = "PurchaseOrderManagementService")
@XmlSeeAlso({budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ObjectFactory.class, budgetuserlibrary.gw.fmis.ibm.hr.messages.ObjectFactory.class, bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.ObjectFactory.class, ObjectFactory.class})
public interface PurchaseOrderManagementService {

    @WebResult(name = "changePurchaseOrderParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "changePurchaseOrder", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice.ChangePurchaseOrder")
    @WebMethod
    @ResponseWrapper(localName = "changePurchaseOrderResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice.ChangePurchaseOrderResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.PurchaseOrderResponseMsg changePurchaseOrder(
        @WebParam(name = "changePurchaseOrderParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.PurchaseOrderChangeRequestMsg changePurchaseOrderParamIn
    );

    @WebResult(name = "createPurchaseOrderParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "createPurchaseOrder", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice.CreatePurchaseOrder")
    @WebMethod
    @ResponseWrapper(localName = "createPurchaseOrderResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice.CreatePurchaseOrderResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.PurchaseOrderResponseMsg createPurchaseOrder(
        @WebParam(name = "createPurchaseOrderParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.PurchaseOrderCreateRequestMsg createPurchaseOrderParamIn
    );

    @WebResult(name = "closePurchaseOrderParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "closePurchaseOrder", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice.ClosePurchaseOrder")
    @WebMethod
    @ResponseWrapper(localName = "closePurchaseOrderResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/PurchaseOrderManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.purchaseordermanagementservice.ClosePurchaseOrderResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.PurchaseOrderResponseMsg closePurchaseOrder(
        @WebParam(name = "closePurchaseOrderParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.PurchaseOrderCloseRequestMsg closePurchaseOrderParamIn
    );
}
