package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-06-20T14:59:33.340+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", name = "VendorManagementInterface")
@XmlSeeAlso({budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ObjectFactory.class, ObjectFactory.class, budgetuserlibrary.gw.fmis.ibm.hr.messages.ObjectFactory.class})
public interface VendorManagementInterface {

    @WebResult(name = "bankAccountResponseMsg", targetNamespace = "")
    @RequestWrapper(localName = "addNewBankAccount", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.AddNewBankAccount")
    @WebMethod
    @ResponseWrapper(localName = "addNewBankAccountResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.AddNewBankAccountResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.BankAccountResponseMsg addNewBankAccount(
        @WebParam(name = "bankAccountCreationRequestMsg", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.BankAccountCreationRequestMsg bankAccountCreationRequestMsg
    );

    @WebResult(name = "requestVendorDeactivationOutput", targetNamespace = "")
    @RequestWrapper(localName = "deactivateVendor", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.DeactivateVendor")
    @WebMethod
    @ResponseWrapper(localName = "deactivateVendorResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.DeactivateVendorResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorResponseMsg deactivateVendor(
        @WebParam(name = "requestVendorDeactivationInput", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorDeactivationRequestMsg requestVendorDeactivationInput
    );

    @WebResult(name = "requestVendorCreationOutput", targetNamespace = "")
    @RequestWrapper(localName = "createVendor", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.CreateVendor")
    @WebMethod
    @ResponseWrapper(localName = "createVendorResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.CreateVendorResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorResponseMsg createVendor(
        @WebParam(name = "requestVendorCreationInput", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorCreationRequestMsg requestVendorCreationInput
    );

    @WebResult(name = "requestVendorChangeOutput", targetNamespace = "")
    @RequestWrapper(localName = "changeVendor", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.ChangeVendor")
    @WebMethod
    @ResponseWrapper(localName = "changeVendorResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.ChangeVendorResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorResponseMsg changeVendor(
        @WebParam(name = "requestVendorChangeInput", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorChangeRequestMsg requestVendorChangeInput
    );

    @WebResult(name = "vendorResponseMsg", targetNamespace = "")
    @RequestWrapper(localName = "retrieveVendor", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.RetrieveVendor")
    @WebMethod
    @ResponseWrapper(localName = "retrieveVendorResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.RetrieveVendorResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorRetrieveResponseMsg retrieveVendor(
        @WebParam(name = "vendorRetrieveRequestMsg", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.VendorRetrieveRequestMsg vendorRetrieveRequestMsg
    );

    @WebResult(name = "bankAccountResponseMsg", targetNamespace = "")
    @RequestWrapper(localName = "deactivateBankAccount", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.DeactivateBankAccount")
    @WebMethod
    @ResponseWrapper(localName = "deactivateBankAccountResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/VendorManagementInterface", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.vendormanagementinterface.DeactivateBankAccountResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.BankAccountResponseMsg deactivateBankAccount(
        @WebParam(name = "bankAccountDeactivateRequestMsg", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.BankAccountDeactivateRequestMsg bankAccountDeactivateRequestMsg
    );
}
