package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-10-14T14:54:55.454+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", name = "ContractManagementService")
@XmlSeeAlso({budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ObjectFactory.class, ObjectFactory.class, budgetuserlibrary.gw.fmis.ibm.hr.messages.ObjectFactory.class, bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.ObjectFactory.class})
public interface ContractManagementService {

    @WebResult(name = "changeContractParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "changeContract", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.ChangeContract")
    @WebMethod
    @ResponseWrapper(localName = "changeContractResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.ChangeContractResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.ContractResponseMsg changeContract(
        @WebParam(name = "changeContractParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.ContractChangeRequestMsg changeContractParamIn
    );

    @WebResult(name = "createContractParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "createContract", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.CreateContract")
    @WebMethod
    @ResponseWrapper(localName = "createContractResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.CreateContractResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.ContractResponseMsg createContract(
        @WebParam(name = "createContractParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.ContractCreateRequestMsg createContractParamIn
    );

    @WebResult(name = "closeContractParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "closeContract", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.CloseContract")
    @WebMethod
    @ResponseWrapper(localName = "closeContractResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.CloseContractResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.ContractResponseMsg closeContract(
        @WebParam(name = "closeContractParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.ContractCloseRequestMsg closeContractParamIn
    );
}
