
package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice.binding.ManageInvoiceExportInvoiceManagementServiceHttpService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2013-03-27T08:50:55.474+01:00
 * Generated source version: 2.4.0
 * 
 */
public final class InvoiceManagementService_ManageInvoiceExportInvoiceManagementServiceHttpPort_Client {

    private static final QName SERVICE_NAME = new QName("http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/InvoiceManagementService/Binding", "manageInvoiceExport_InvoiceManagementServiceHttpService");

    private InvoiceManagementService_ManageInvoiceExportInvoiceManagementServiceHttpPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = ManageInvoiceExportInvoiceManagementServiceHttpService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ManageInvoiceExportInvoiceManagementServiceHttpService ss = new ManageInvoiceExportInvoiceManagementServiceHttpService(wsdlURL, SERVICE_NAME);
        InvoiceManagementService port = ss.getManageInvoiceExportInvoiceManagementServiceHttpPort();  
        
        {
        System.out.println("Invoking changeInvoice...");
        budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceChangeRequestMsg _changeInvoice_invoiceChangeRequestMsg = new budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceChangeRequestMsg();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader _changeInvoice_invoiceChangeRequestMsgMessageHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader();
        _changeInvoice_invoiceChangeRequestMsgMessageHeader.setSubmitionTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.580+01:00"));
        _changeInvoice_invoiceChangeRequestMsgMessageHeader.setResponseMsgId(Long.valueOf(4608616888631251080l));
        _changeInvoice_invoiceChangeRequestMsgMessageHeader.setEventId(Long.valueOf(-5863380650551242350l));
        _changeInvoice_invoiceChangeRequestMsg.setMessageHeader(_changeInvoice_invoiceChangeRequestMsgMessageHeader);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice _changeInvoice_invoiceChangeRequestMsgInvoice = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.PENDING_APPROVAL;
        _changeInvoice_invoiceChangeRequestMsgInvoice.setInvoiceStatus(_changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceStatus);
        bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader = new bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader();
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setLogicalSystemName("LogicalSystemName1607407246");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setBudgetUser("BudgetUser-1779053692");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setBuFmisDocumentId("BuFmisDocumentId-1950368744");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.584+01:00"));
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setReference("Reference-363797031");
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderCurrency = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency();
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderCurrency.setName("Name-1466990276");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderCurrency.setCode("Code-246184539");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderCurrency.setCodeNum("CodeNum1604149559");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setCurrency(_changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderCurrency);
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.585+01:00"));
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setDescription("Description689746775");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setCompanyCode("CompanyCode-1754644852");
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategory = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentClass = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType.GL_TRANSFER;
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategory.setDocumentClass(_changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentClass);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType.GL_TRANSFER;
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategory.setDocumentCategory(_changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory);
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategory.setDocumentType("DocumentType1494325130");
        _changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader.setDocumentClassCategory(_changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeaderDocumentClassCategory);
        _changeInvoice_invoiceChangeRequestMsgInvoice.setDocumentHeader(_changeInvoice_invoiceChangeRequestMsgInvoiceDocumentHeader);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList _changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList();
        java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem> _changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceItemListInvoiceItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem>();
        _changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceItemList.getInvoiceItem().addAll(_changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceItemListInvoiceItem);
        _changeInvoice_invoiceChangeRequestMsgInvoice.setInvoiceItemList(_changeInvoice_invoiceChangeRequestMsgInvoiceInvoiceItemList);
        _changeInvoice_invoiceChangeRequestMsgInvoice.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.586+01:00"));
        _changeInvoice_invoiceChangeRequestMsgInvoice.setAmount(new java.math.BigDecimal("7074962445149499065.6053685372232479206"));
        _changeInvoice_invoiceChangeRequestMsgInvoice.setLocalCurrencyAmount(new java.math.BigDecimal("-7144038224816402296.555731634283039085"));
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList _changeInvoice_invoiceChangeRequestMsgInvoiceVendorItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList();
        java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem> _changeInvoice_invoiceChangeRequestMsgInvoiceVendorItemListVendorItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem>();
        _changeInvoice_invoiceChangeRequestMsgInvoiceVendorItemList.getVendorItem().addAll(_changeInvoice_invoiceChangeRequestMsgInvoiceVendorItemListVendorItem);
        _changeInvoice_invoiceChangeRequestMsgInvoice.setVendorItemList(_changeInvoice_invoiceChangeRequestMsgInvoiceVendorItemList);
        _changeInvoice_invoiceChangeRequestMsgInvoice.setIsCession(Boolean.valueOf(true));
        _changeInvoice_invoiceChangeRequestMsgInvoice.setDocumentBlock("DocumentBlock-1331217168");
        _changeInvoice_invoiceChangeRequestMsgInvoice.setCreditMemoBuFmisDocumentId("CreditMemoBuFmisDocumentId-751728944");
        _changeInvoice_invoiceChangeRequestMsg.setInvoice(_changeInvoice_invoiceChangeRequestMsgInvoice);
        budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg _changeInvoice__return = port.changeInvoice(_changeInvoice_invoiceChangeRequestMsg);
        System.out.println("changeInvoice.result=" + _changeInvoice__return);


        }
        {
        System.out.println("Invoking reverseInvoice...");
        budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceReverseRequestMsg _reverseInvoice_invoiceReverseRequestMsg = new budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceReverseRequestMsg();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader _reverseInvoice_invoiceReverseRequestMsgMessageHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader();
        _reverseInvoice_invoiceReverseRequestMsgMessageHeader.setSubmitionTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.596+01:00"));
        _reverseInvoice_invoiceReverseRequestMsgMessageHeader.setResponseMsgId(Long.valueOf(5062353137916699190l));
        _reverseInvoice_invoiceReverseRequestMsgMessageHeader.setEventId(Long.valueOf(-5199366993563221638l));
        _reverseInvoice_invoiceReverseRequestMsg.setMessageHeader(_reverseInvoice_invoiceReverseRequestMsgMessageHeader);
        bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader _reverseInvoice_invoiceReverseRequestMsgInvoice = new bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader();
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setLogicalSystemName("LogicalSystemName-844767959");
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setBudgetUser("BudgetUser1784978534");
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setBuFmisDocumentId("BuFmisDocumentId-1399778127");
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.597+01:00"));
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setReference("Reference218162355");
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency _reverseInvoice_invoiceReverseRequestMsgInvoiceCurrency = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency();
        _reverseInvoice_invoiceReverseRequestMsgInvoiceCurrency.setName("Name2055642801");
        _reverseInvoice_invoiceReverseRequestMsgInvoiceCurrency.setCode("Code-1891177189");
        _reverseInvoice_invoiceReverseRequestMsgInvoiceCurrency.setCodeNum("CodeNum538624145");
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setCurrency(_reverseInvoice_invoiceReverseRequestMsgInvoiceCurrency);
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.598+01:00"));
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setDescription("Description26249981");
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setCompanyCode("CompanyCode-887339811");
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType _reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategory = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType _reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategoryDocumentClass = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType.PAYMENT_REQUEST;
        _reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategory.setDocumentClass(_reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategoryDocumentClass);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType _reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategoryDocumentCategory = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType.INVOICE;
        _reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategory.setDocumentCategory(_reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategoryDocumentCategory);
        _reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategory.setDocumentType("DocumentType-941854816");
        _reverseInvoice_invoiceReverseRequestMsgInvoice.setDocumentClassCategory(_reverseInvoice_invoiceReverseRequestMsgInvoiceDocumentClassCategory);
        _reverseInvoice_invoiceReverseRequestMsg.setInvoice(_reverseInvoice_invoiceReverseRequestMsgInvoice);
        _reverseInvoice_invoiceReverseRequestMsg.setBuFmisDocumentIdToReverse("BuFmisDocumentIdToReverse922851166");
        budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg _reverseInvoice__return = port.reverseInvoice(_reverseInvoice_invoiceReverseRequestMsg);
        System.out.println("reverseInvoice.result=" + _reverseInvoice__return);


        }
        {
        System.out.println("Invoking createInvoice...");
        budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceCreateRequestMsg _createInvoice_invoiceCreateRequestMsg = new budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceCreateRequestMsg();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader _createInvoice_invoiceCreateRequestMsgMessageHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader();
        _createInvoice_invoiceCreateRequestMsgMessageHeader.setSubmitionTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.600+01:00"));
        _createInvoice_invoiceCreateRequestMsgMessageHeader.setResponseMsgId(Long.valueOf(-4414318638901677403l));
        _createInvoice_invoiceCreateRequestMsgMessageHeader.setEventId(Long.valueOf(1795963118624087448l));
        _createInvoice_invoiceCreateRequestMsg.setMessageHeader(_createInvoice_invoiceCreateRequestMsgMessageHeader);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice _createInvoice_invoiceCreateRequestMsgInvoice = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _createInvoice_invoiceCreateRequestMsgInvoiceInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.DENIED;
        _createInvoice_invoiceCreateRequestMsgInvoice.setInvoiceStatus(_createInvoice_invoiceCreateRequestMsgInvoiceInvoiceStatus);
        bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader = new bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader();
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setLogicalSystemName("LogicalSystemName-1211713822");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setBudgetUser("BudgetUser-256659753");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setBuFmisDocumentId("BuFmisDocumentId1526504158");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.602+01:00"));
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setReference("Reference670151070");
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderCurrency = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency();
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderCurrency.setName("Name-1505806580");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderCurrency.setCode("Code369403787");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderCurrency.setCodeNum("CodeNum-628287008");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setCurrency(_createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderCurrency);
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.602+01:00"));
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setDescription("Description-1427664768");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setCompanyCode("CompanyCode-978912759");
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategory = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType();
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentClass = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType.GL_TRANSFER;
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategory.setDocumentClass(_createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentClass);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType.PURCHASE_ORDER;
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategory.setDocumentCategory(_createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory);
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategory.setDocumentType("DocumentType1598001612");
        _createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader.setDocumentClassCategory(_createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeaderDocumentClassCategory);
        _createInvoice_invoiceCreateRequestMsgInvoice.setDocumentHeader(_createInvoice_invoiceCreateRequestMsgInvoiceDocumentHeader);
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList _createInvoice_invoiceCreateRequestMsgInvoiceInvoiceItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList();
        java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem> _createInvoice_invoiceCreateRequestMsgInvoiceInvoiceItemListInvoiceItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem>();
        _createInvoice_invoiceCreateRequestMsgInvoiceInvoiceItemList.getInvoiceItem().addAll(_createInvoice_invoiceCreateRequestMsgInvoiceInvoiceItemListInvoiceItem);
        _createInvoice_invoiceCreateRequestMsgInvoice.setInvoiceItemList(_createInvoice_invoiceCreateRequestMsgInvoiceInvoiceItemList);
        _createInvoice_invoiceCreateRequestMsgInvoice.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.603+01:00"));
        _createInvoice_invoiceCreateRequestMsgInvoice.setAmount(new java.math.BigDecimal("8288898368299970112.1102893535710027998"));
        _createInvoice_invoiceCreateRequestMsgInvoice.setLocalCurrencyAmount(new java.math.BigDecimal("-7658963625016939842.5351796192754499551"));
        budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList _createInvoice_invoiceCreateRequestMsgInvoiceVendorItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList();
        java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem> _createInvoice_invoiceCreateRequestMsgInvoiceVendorItemListVendorItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem>();
        _createInvoice_invoiceCreateRequestMsgInvoiceVendorItemList.getVendorItem().addAll(_createInvoice_invoiceCreateRequestMsgInvoiceVendorItemListVendorItem);
        _createInvoice_invoiceCreateRequestMsgInvoice.setVendorItemList(_createInvoice_invoiceCreateRequestMsgInvoiceVendorItemList);
        _createInvoice_invoiceCreateRequestMsgInvoice.setIsCession(Boolean.valueOf(true));
        _createInvoice_invoiceCreateRequestMsgInvoice.setDocumentBlock("DocumentBlock1202370636");
        _createInvoice_invoiceCreateRequestMsgInvoice.setCreditMemoBuFmisDocumentId("CreditMemoBuFmisDocumentId-1717640854");
        _createInvoice_invoiceCreateRequestMsg.setInvoice(_createInvoice_invoiceCreateRequestMsgInvoice);
        budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg _createInvoice__return = port.createInvoice(_createInvoice_invoiceCreateRequestMsg);
        System.out.println("createInvoice.result=" + _createInvoice__return);


        }

        System.exit(0);
    }

}
