
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2013-03-27T08:50:55.613+01:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "manageInvoiceExport_InvoiceManagementServiceHttpService",
                      portName = "manageInvoiceExport_InvoiceManagementServiceHttpPort",
                      targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/InvoiceManagementService/Binding",
                      wsdlLocation = "http://localhost:8080/Infomare_drrh_web_services/services/manageInvoiceExport_InvoiceManagementServiceHttpPort?wsdl",
                      endpointInterface = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice.InvoiceManagementService")
                      
public class InvoiceManagementServiceImpl implements InvoiceManagementService {

    private static final Logger LOG = Logger.getLogger(InvoiceManagementServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice.InvoiceManagementService#changeInvoice(budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceChangeRequestMsg  invoiceChangeRequestMsg )*
     */
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg changeInvoice(budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceChangeRequestMsg invoiceChangeRequestMsg) { 
        LOG.info("Executing operation changeInvoice");
        System.out.println(invoiceChangeRequestMsg);
        try {
            budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg _return = new budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ResponseMessageType _returnResponseMessageType = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ResponseMessageType.NOTIFICATION;
            _return.setResponseMessageType(_returnResponseMessageType);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ErrorResponse _returnErrorResponse = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ErrorResponse();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error> _returnErrorResponseError = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error>();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error _returnErrorResponseErrorVal1 = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error();
            _returnErrorResponseErrorVal1.setTarget("Target-364063855");
            _returnErrorResponseErrorVal1.setValue("Value1991171844");
            _returnErrorResponseErrorVal1.setErrorCode("ErrorCode706418347");
            _returnErrorResponseErrorVal1.setDescription("Description-2018330566");
            _returnErrorResponseError.add(_returnErrorResponseErrorVal1);
            _returnErrorResponse.getError().addAll(_returnErrorResponseError);
            _return.setErrorResponse(_returnErrorResponse);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusNotification _returnNotificationResponse = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusNotification();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.NotificationHeader _returnNotificationResponseHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.NotificationHeader();
            _returnNotificationResponseHeader.setNotifiedBudgetUser("NotifiedBudgetUser-1783962604");
            _returnNotificationResponseHeader.setNotifiedLogicalSystemName("NotifiedLogicalSystemName-1488363730");
            _returnNotificationResponseHeader.setFmisGwNotificationId("FmisGwNotificationId1062247290");
            _returnNotificationResponseHeader.setOriginatingBuFmisDocumentID("OriginatingBuFmisDocumentID-863840522");
            _returnNotificationResponseHeader.setSapDocumentId("SapDocumentId-1187127134");
            _returnNotificationResponseHeader.setNotificationDate("NotificationDate1256136642");
            _returnNotificationResponse.setHeader(_returnNotificationResponseHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _returnNotificationResponseInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.APPROVED;
            _returnNotificationResponse.setInvoiceStatus(_returnNotificationResponseInvoiceStatus);
            _returnNotificationResponse.setDescription("Description-74869407");
            _return.setNotificationResponse(_returnNotificationResponse);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader _returnMessageHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader();
            _returnMessageHeader.setSubmitionTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.655+01:00"));
            _returnMessageHeader.setResponseMsgId(Long.valueOf(-1994602825606233814l));
            _returnMessageHeader.setEventId(Long.valueOf(3690378494048974165l));
            _return.setMessageHeader(_returnMessageHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice _returnInvoice = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _returnInvoiceInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.DENIED;
            _returnInvoice.setInvoiceStatus(_returnInvoiceInvoiceStatus);
            bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader _returnInvoiceDocumentHeader = new bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader();
            _returnInvoiceDocumentHeader.setLogicalSystemName("LogicalSystemName606312523");
            _returnInvoiceDocumentHeader.setBudgetUser("BudgetUser938907584");
            _returnInvoiceDocumentHeader.setBuFmisDocumentId("BuFmisDocumentId74166400");
            _returnInvoiceDocumentHeader.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.656+01:00"));
            _returnInvoiceDocumentHeader.setReference("Reference1657054717");
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency _returnInvoiceDocumentHeaderCurrency = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency();
            _returnInvoiceDocumentHeaderCurrency.setName("Name-1425533498");
            _returnInvoiceDocumentHeaderCurrency.setCode("Code-331453098");
            _returnInvoiceDocumentHeaderCurrency.setCodeNum("CodeNum1531394885");
            _returnInvoiceDocumentHeader.setCurrency(_returnInvoiceDocumentHeaderCurrency);
            _returnInvoiceDocumentHeader.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.658+01:00"));
            _returnInvoiceDocumentHeader.setDescription("Description1823763372");
            _returnInvoiceDocumentHeader.setCompanyCode("CompanyCode-226370182");
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType _returnInvoiceDocumentHeaderDocumentClassCategory = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType _returnInvoiceDocumentHeaderDocumentClassCategoryDocumentClass = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType.INVOICE;
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentClass(_returnInvoiceDocumentHeaderDocumentClassCategoryDocumentClass);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType _returnInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType.BUDGET_PLAN;
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentCategory(_returnInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory);
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentType("DocumentType671568427");
            _returnInvoiceDocumentHeader.setDocumentClassCategory(_returnInvoiceDocumentHeaderDocumentClassCategory);
            _returnInvoice.setDocumentHeader(_returnInvoiceDocumentHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList _returnInvoiceInvoiceItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem> _returnInvoiceInvoiceItemListInvoiceItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem>();
            _returnInvoiceInvoiceItemList.getInvoiceItem().addAll(_returnInvoiceInvoiceItemListInvoiceItem);
            _returnInvoice.setInvoiceItemList(_returnInvoiceInvoiceItemList);
            _returnInvoice.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.658+01:00"));
            _returnInvoice.setAmount(new java.math.BigDecimal("-5265110053629804504.6479848808731880629"));
            _returnInvoice.setLocalCurrencyAmount(new java.math.BigDecimal("8964021623952365669.8507283747262111406"));
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList _returnInvoiceVendorItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem> _returnInvoiceVendorItemListVendorItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem>();
            _returnInvoiceVendorItemList.getVendorItem().addAll(_returnInvoiceVendorItemListVendorItem);
            _returnInvoice.setVendorItemList(_returnInvoiceVendorItemList);
            _returnInvoice.setIsCession(Boolean.valueOf(false));
            _returnInvoice.setDocumentBlock("DocumentBlock-45710634");
            _returnInvoice.setCreditMemoBuFmisDocumentId("CreditMemoBuFmisDocumentId-150900736");
            _return.setInvoice(_returnInvoice);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice.InvoiceManagementService#reverseInvoice(budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceReverseRequestMsg  invoiceReverseRequestMsg )*
     */
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg reverseInvoice(budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceReverseRequestMsg invoiceReverseRequestMsg) { 
        LOG.info("Executing operation reverseInvoice");
        System.out.println(invoiceReverseRequestMsg);
        try {
            budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg _return = new budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ResponseMessageType _returnResponseMessageType = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ResponseMessageType.ERROR;
            _return.setResponseMessageType(_returnResponseMessageType);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ErrorResponse _returnErrorResponse = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ErrorResponse();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error> _returnErrorResponseError = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error>();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error _returnErrorResponseErrorVal1 = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error();
            _returnErrorResponseErrorVal1.setTarget("Target-590820415");
            _returnErrorResponseErrorVal1.setValue("Value807266591");
            _returnErrorResponseErrorVal1.setErrorCode("ErrorCode295470952");
            _returnErrorResponseErrorVal1.setDescription("Description-1933390415");
            _returnErrorResponseError.add(_returnErrorResponseErrorVal1);
            _returnErrorResponse.getError().addAll(_returnErrorResponseError);
            _return.setErrorResponse(_returnErrorResponse);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusNotification _returnNotificationResponse = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusNotification();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.NotificationHeader _returnNotificationResponseHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.NotificationHeader();
            _returnNotificationResponseHeader.setNotifiedBudgetUser("NotifiedBudgetUser1729681439");
            _returnNotificationResponseHeader.setNotifiedLogicalSystemName("NotifiedLogicalSystemName-1279193723");
            _returnNotificationResponseHeader.setFmisGwNotificationId("FmisGwNotificationId-1507090666");
            _returnNotificationResponseHeader.setOriginatingBuFmisDocumentID("OriginatingBuFmisDocumentID1343083702");
            _returnNotificationResponseHeader.setSapDocumentId("SapDocumentId-423096673");
            _returnNotificationResponseHeader.setNotificationDate("NotificationDate1885892000");
            _returnNotificationResponse.setHeader(_returnNotificationResponseHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _returnNotificationResponseInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.APPROVED;
            _returnNotificationResponse.setInvoiceStatus(_returnNotificationResponseInvoiceStatus);
            _returnNotificationResponse.setDescription("Description787521331");
            _return.setNotificationResponse(_returnNotificationResponse);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader _returnMessageHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader();
            _returnMessageHeader.setSubmitionTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.661+01:00"));
            _returnMessageHeader.setResponseMsgId(Long.valueOf(-7800118744584381362l));
            _returnMessageHeader.setEventId(Long.valueOf(-2374321317257568222l));
            _return.setMessageHeader(_returnMessageHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice _returnInvoice = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _returnInvoiceInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.REVERSE;
            _returnInvoice.setInvoiceStatus(_returnInvoiceInvoiceStatus);
            bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader _returnInvoiceDocumentHeader = new bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader();
            _returnInvoiceDocumentHeader.setLogicalSystemName("LogicalSystemName-988412181");
            _returnInvoiceDocumentHeader.setBudgetUser("BudgetUser290196015");
            _returnInvoiceDocumentHeader.setBuFmisDocumentId("BuFmisDocumentId982562697");
            _returnInvoiceDocumentHeader.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.662+01:00"));
            _returnInvoiceDocumentHeader.setReference("Reference-416732344");
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency _returnInvoiceDocumentHeaderCurrency = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency();
            _returnInvoiceDocumentHeaderCurrency.setName("Name327768510");
            _returnInvoiceDocumentHeaderCurrency.setCode("Code-238637470");
            _returnInvoiceDocumentHeaderCurrency.setCodeNum("CodeNum747433490");
            _returnInvoiceDocumentHeader.setCurrency(_returnInvoiceDocumentHeaderCurrency);
            _returnInvoiceDocumentHeader.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.666+01:00"));
            _returnInvoiceDocumentHeader.setDescription("Description-1547005986");
            _returnInvoiceDocumentHeader.setCompanyCode("CompanyCode-1508296779");
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType _returnInvoiceDocumentHeaderDocumentClassCategory = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType _returnInvoiceDocumentHeaderDocumentClassCategoryDocumentClass = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType.PAYMENT_EXECUTION;
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentClass(_returnInvoiceDocumentHeaderDocumentClassCategoryDocumentClass);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType _returnInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType.BUDGET_PLAN;
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentCategory(_returnInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory);
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentType("DocumentType-887120996");
            _returnInvoiceDocumentHeader.setDocumentClassCategory(_returnInvoiceDocumentHeaderDocumentClassCategory);
            _returnInvoice.setDocumentHeader(_returnInvoiceDocumentHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList _returnInvoiceInvoiceItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem> _returnInvoiceInvoiceItemListInvoiceItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem>();
            _returnInvoiceInvoiceItemList.getInvoiceItem().addAll(_returnInvoiceInvoiceItemListInvoiceItem);
            _returnInvoice.setInvoiceItemList(_returnInvoiceInvoiceItemList);
            _returnInvoice.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.668+01:00"));
            _returnInvoice.setAmount(new java.math.BigDecimal("-4453715518212456005.3720435675825943197"));
            _returnInvoice.setLocalCurrencyAmount(new java.math.BigDecimal("8838708903882211515.1725341955910180686"));
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList _returnInvoiceVendorItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem> _returnInvoiceVendorItemListVendorItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem>();
            _returnInvoiceVendorItemList.getVendorItem().addAll(_returnInvoiceVendorItemListVendorItem);
            _returnInvoice.setVendorItemList(_returnInvoiceVendorItemList);
            _returnInvoice.setIsCession(Boolean.valueOf(false));
            _returnInvoice.setDocumentBlock("DocumentBlock-105279668");
            _returnInvoice.setCreditMemoBuFmisDocumentId("CreditMemoBuFmisDocumentId902138907");
            _return.setInvoice(_returnInvoice);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.invoicemanagementservice.InvoiceManagementService#createInvoice(budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceCreateRequestMsg  invoiceCreateRequestMsg )*
     */
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg createInvoice(budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceCreateRequestMsg invoiceCreateRequestMsg) { 
        LOG.info("Executing operation createInvoice");
        System.out.println(invoiceCreateRequestMsg);
        try {
            budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg _return = new budgetuserlibrary.gw.fmis.ibm.hr.messages.InvoiceResponseMsg();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ResponseMessageType _returnResponseMessageType = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ResponseMessageType.ERROR;
            _return.setResponseMessageType(_returnResponseMessageType);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ErrorResponse _returnErrorResponse = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ErrorResponse();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error> _returnErrorResponseError = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error>();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error _returnErrorResponseErrorVal1 = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Error();
            _returnErrorResponseErrorVal1.setTarget("Target-1826639318");
            _returnErrorResponseErrorVal1.setValue("Value-762996896");
            _returnErrorResponseErrorVal1.setErrorCode("ErrorCode-1378378192");
            _returnErrorResponseErrorVal1.setDescription("Description2038177330");
            _returnErrorResponseError.add(_returnErrorResponseErrorVal1);
            _returnErrorResponse.getError().addAll(_returnErrorResponseError);
            _return.setErrorResponse(_returnErrorResponse);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusNotification _returnNotificationResponse = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusNotification();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.NotificationHeader _returnNotificationResponseHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.NotificationHeader();
            _returnNotificationResponseHeader.setNotifiedBudgetUser("NotifiedBudgetUser-1985222466");
            _returnNotificationResponseHeader.setNotifiedLogicalSystemName("NotifiedLogicalSystemName340278751");
            _returnNotificationResponseHeader.setFmisGwNotificationId("FmisGwNotificationId1653902963");
            _returnNotificationResponseHeader.setOriginatingBuFmisDocumentID("OriginatingBuFmisDocumentID2000094245");
            _returnNotificationResponseHeader.setSapDocumentId("SapDocumentId1907068997");
            _returnNotificationResponseHeader.setNotificationDate("NotificationDate172094411");
            _returnNotificationResponse.setHeader(_returnNotificationResponseHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _returnNotificationResponseInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.DENIED;
            _returnNotificationResponse.setInvoiceStatus(_returnNotificationResponseInvoiceStatus);
            _returnNotificationResponse.setDescription("Description415652229");
            _return.setNotificationResponse(_returnNotificationResponse);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader _returnMessageHeader = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader();
            _returnMessageHeader.setSubmitionTimestamp(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.673+01:00"));
            _returnMessageHeader.setResponseMsgId(Long.valueOf(3809371099792422309l));
            _returnMessageHeader.setEventId(Long.valueOf(-3230131183242661148l));
            _return.setMessageHeader(_returnMessageHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice _returnInvoice = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Invoice();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType _returnInvoiceInvoiceStatus = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceStatusType.DENIED;
            _returnInvoice.setInvoiceStatus(_returnInvoiceInvoiceStatus);
            bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader _returnInvoiceDocumentHeader = new bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.DocumentHeader();
            _returnInvoiceDocumentHeader.setLogicalSystemName("LogicalSystemName-1225188082");
            _returnInvoiceDocumentHeader.setBudgetUser("BudgetUser1690620161");
            _returnInvoiceDocumentHeader.setBuFmisDocumentId("BuFmisDocumentId-1523552675");
            _returnInvoiceDocumentHeader.setDocumentDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.674+01:00"));
            _returnInvoiceDocumentHeader.setReference("Reference1140955294");
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency _returnInvoiceDocumentHeaderCurrency = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.Currency();
            _returnInvoiceDocumentHeaderCurrency.setName("Name-731912014");
            _returnInvoiceDocumentHeaderCurrency.setCode("Code-1831676289");
            _returnInvoiceDocumentHeaderCurrency.setCodeNum("CodeNum-2132387809");
            _returnInvoiceDocumentHeader.setCurrency(_returnInvoiceDocumentHeaderCurrency);
            _returnInvoiceDocumentHeader.setPostingDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.675+01:00"));
            _returnInvoiceDocumentHeader.setDescription("Description-1012654753");
            _returnInvoiceDocumentHeader.setCompanyCode("CompanyCode1404018273");
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType _returnInvoiceDocumentHeaderDocumentClassCategory = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassCategoryType();
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType _returnInvoiceDocumentHeaderDocumentClassCategoryDocumentClass = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentClassType.PAYMENT_EXECUTION;
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentClass(_returnInvoiceDocumentHeaderDocumentClassCategoryDocumentClass);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType _returnInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory = budgetuserlibrary.gw.fmis.ibm.hr.infotypes.DocumentCategoryType.RESERVATION;
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentCategory(_returnInvoiceDocumentHeaderDocumentClassCategoryDocumentCategory);
            _returnInvoiceDocumentHeaderDocumentClassCategory.setDocumentType("DocumentType-1851719714");
            _returnInvoiceDocumentHeader.setDocumentClassCategory(_returnInvoiceDocumentHeaderDocumentClassCategory);
            _returnInvoice.setDocumentHeader(_returnInvoiceDocumentHeader);
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList _returnInvoiceInvoiceItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.IncoiceItemList();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem> _returnInvoiceInvoiceItemListInvoiceItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.InvoiceItem>();
            _returnInvoiceInvoiceItemList.getInvoiceItem().addAll(_returnInvoiceInvoiceItemListInvoiceItem);
            _returnInvoice.setInvoiceItemList(_returnInvoiceInvoiceItemList);
            _returnInvoice.setDueDate(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2013-03-27T08:50:55.676+01:00"));
            _returnInvoice.setAmount(new java.math.BigDecimal("-6611517907636902039.4376032482295713414"));
            _returnInvoice.setLocalCurrencyAmount(new java.math.BigDecimal("5414636938536162394.4231996444553189812"));
            budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList _returnInvoiceVendorItemList = new budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItemList();
            java.util.List<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem> _returnInvoiceVendorItemListVendorItem = new java.util.ArrayList<budgetuserlibrary.gw.fmis.ibm.hr.infotypes.VendorItem>();
            _returnInvoiceVendorItemList.getVendorItem().addAll(_returnInvoiceVendorItemListVendorItem);
            _returnInvoice.setVendorItemList(_returnInvoiceVendorItemList);
            _returnInvoice.setIsCession(Boolean.valueOf(true));
            _returnInvoice.setDocumentBlock("DocumentBlock1280333448");
            _returnInvoice.setCreditMemoBuFmisDocumentId("CreditMemoBuFmisDocumentId-1499070556");
            _return.setInvoice(_returnInvoice);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
