
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-05T12:37:57.019+01:00
 * Generated source version: 2.4.0
 * 
 */

@javax.jws.WebService(
                      serviceName = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpService",
                      portName = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort",
                      targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/Binding2",
                      wsdlLocation = "http://localhost:8080/Infomare_drrh_web_services/services/ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort?wsdl",
                      endpointInterface = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService")
                      
public class ResponseMessageHandlerServiceImpl implements ResponseMessageHandlerService {

    private static final Logger LOG = Logger.getLogger(ResponseMessageHandlerServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getPaymentExecutionListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getPaymentExecutionListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getPaymentExecutionListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getPurchaseOrderResponseListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getPurchaseOrderResponseListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getPurchaseOrderResponseListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getVendorUpdatesListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getVendorUpdatesListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getVendorUpdatesListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getReservationResponseListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getReservationResponseListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getReservationResponseListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getContractResponseList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getContractResponseList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getContractResponseList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getBankUpdatesList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getBankUpdatesList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getBankUpdatesList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getBankUpdatesListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getBankUpdatesListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getBankUpdatesListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getVendorUpdatesList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getVendorUpdatesList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getVendorUpdatesList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getInvoiceResponseList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getInvoiceResponseList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getInvoiceResponseList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getAllResponseList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getAllResponseList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getAllResponseList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getReservationResponseList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getReservationResponseList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getReservationResponseList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getInvoiceResponseListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getInvoiceResponseListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getInvoiceResponseListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getContractResponseListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getContractResponseListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getContractResponseListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getPurchaseOrderResponseList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getPurchaseOrderResponseList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getPurchaseOrderResponseList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getPaymentExecutionList(java.lang.String  logicalSystemName )*
     */
    public java.lang.Object getPaymentExecutionList(java.lang.String logicalSystemName) { 
        LOG.info("Executing operation getPaymentExecutionList");
        System.out.println(logicalSystemName);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService#getAllResponseListStartingWithMessageId(java.lang.String  logicalSystemName ,)java.lang.Long  messageId )*
     */
    public java.lang.Object getAllResponseListStartingWithMessageId(java.lang.String logicalSystemName,java.lang.Long messageId) { 
        LOG.info("Executing operation getAllResponseListStartingWithMessageId");
        System.out.println(logicalSystemName);
        System.out.println(messageId);
        try {
            java.lang.Object _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
