package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-05T12:37:57.081+01:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", name = "ResponseMessageHandlerService")
@XmlSeeAlso({ budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ObjectFactory.class,
	budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.ObjectFactory.class,
	budgetuserlibrary.gw.fmis.ibm.hr.messages.ObjectFactory.class})
public interface ResponseMessageHandlerService {

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getPaymentExecutionListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPaymentExecutionListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getPaymentExecutionListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPaymentExecutionListStartingWithMessageIdResponse")
    public java.lang.Object getPaymentExecutionListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getPurchaseOrderResponseListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPurchaseOrderResponseListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getPurchaseOrderResponseListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPurchaseOrderResponseListStartingWithMessageIdResponse")
    public java.lang.Object getPurchaseOrderResponseListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getVendorUpdatesListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetVendorUpdatesListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getVendorUpdatesListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetVendorUpdatesListStartingWithMessageIdResponse")
    public java.lang.Object getVendorUpdatesListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getReservationResponseListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetReservationResponseListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getReservationResponseListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetReservationResponseListStartingWithMessageIdResponse")
    public java.lang.Object getReservationResponseListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "contractResponseList", targetNamespace = "")
    @RequestWrapper(localName = "getContractResponseList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetContractResponseList")
    @WebMethod
    @ResponseWrapper(localName = "getContractResponseListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetContractResponseListResponse")
    public java.lang.Object getContractResponseList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "bankUpdatesList", targetNamespace = "")
    @RequestWrapper(localName = "getBankUpdatesList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetBankUpdatesList")
    @WebMethod
    @ResponseWrapper(localName = "getBankUpdatesListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetBankUpdatesListResponse")
    public java.lang.Object getBankUpdatesList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getBankUpdatesListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetBankUpdatesListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getBankUpdatesListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetBankUpdatesListStartingWithMessageIdResponse")
    public java.lang.Object getBankUpdatesListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "vendorUpdatesList", targetNamespace = "")
    @RequestWrapper(localName = "getVendorUpdatesList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetVendorUpdatesList")
    @WebMethod
    @ResponseWrapper(localName = "getVendorUpdatesListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetVendorUpdatesListResponse")
    public java.lang.Object getVendorUpdatesList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "invoiceResponseList", targetNamespace = "")
    @RequestWrapper(localName = "getInvoiceResponseList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetInvoiceResponseList")
    @WebMethod
    @ResponseWrapper(localName = "getInvoiceResponseListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetInvoiceResponseListResponse")
    public java.lang.Object getInvoiceResponseList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getAllResponseList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetAllResponseList")
    @WebMethod
    @ResponseWrapper(localName = "getAllResponseListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetAllResponseListResponse")
    public java.lang.Object getAllResponseList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "reservationResponseList", targetNamespace = "")
    @RequestWrapper(localName = "getReservationResponseList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetReservationResponseList")
    @WebMethod
    @ResponseWrapper(localName = "getReservationResponseListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetReservationResponseListResponse")
    public java.lang.Object getReservationResponseList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getInvoiceResponseListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetInvoiceResponseListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getInvoiceResponseListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetInvoiceResponseListStartingWithMessageIdResponse")
    public java.lang.Object getInvoiceResponseListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getContractResponseListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetContractResponseListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getContractResponseListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetContractResponseListStartingWithMessageIdResponse")
    public java.lang.Object getContractResponseListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );

    @WebResult(name = "purchaseOrderResponseList", targetNamespace = "")
    @RequestWrapper(localName = "getPurchaseOrderResponseList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPurchaseOrderResponseList")
    @WebMethod
    @ResponseWrapper(localName = "getPurchaseOrderResponseListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPurchaseOrderResponseListResponse")
    public java.lang.Object getPurchaseOrderResponseList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "paymentExecutionList", targetNamespace = "")
    @RequestWrapper(localName = "getPaymentExecutionList", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPaymentExecutionList")
    @WebMethod
    @ResponseWrapper(localName = "getPaymentExecutionListResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetPaymentExecutionListResponse")
    public java.lang.Object getPaymentExecutionList(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName
    );

    @WebResult(name = "distributionMessageList", targetNamespace = "")
    @RequestWrapper(localName = "getAllResponseListStartingWithMessageId", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetAllResponseListStartingWithMessageId")
    @WebMethod
    @ResponseWrapper(localName = "getAllResponseListStartingWithMessageIdResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.GetAllResponseListStartingWithMessageIdResponse")
    public java.lang.Object getAllResponseListStartingWithMessageId(
        @WebParam(name = "logicalSystemName", targetNamespace = "")
        java.lang.String logicalSystemName,
        @WebParam(name = "messageId", targetNamespace = "")
        java.lang.Long messageId
    );
}
