package hr.infomare.drrh.pojo;

// Generated 16.06.2011. 15:40:00 by Hibernate Tools 3.2.1.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Bankmsg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "BANKMSG")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Bankmsg implements java.io.Serializable {

	private int idBankmsg;
	private Reqmsg reqmsg;
	private String f47ctr;
	private byte opt;
	private String vbdi;
	private String name;
	private String swift;
	private String street;
	private String streetnum;
	private String city;
	private String zipcode;
	private String countryco;
	private byte status;
	private String user;
	private int datetime;
	private Date datetimews;
	private Date timews;

	public Bankmsg() {
	}

	@Id
	@Column(name = "ID_BANKMSG", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdBankmsg() {
		return this.idBankmsg;
	}

	public void setIdBankmsg(int idBankmsg) {
		this.idBankmsg = idBankmsg;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQMSGID")
	public Reqmsg getReqmsg() {
		return this.reqmsg;
	}

	public void setReqmsg(Reqmsg reqmsg) {
		this.reqmsg = reqmsg;
	}

	@Column(name = "F47CTR", nullable = false, length = 7)
	public String getF47ctr() {
		return this.f47ctr;
	}

	public void setF47ctr(String f47ctr) {
		this.f47ctr = f47ctr;
	}

	@Column(name = "OPT", nullable = false, precision = 2, scale = 0)
	public byte getOpt() {
		return this.opt;
	}

	public void setOpt(byte opt) {
		this.opt = opt;
	}

	@Column(name = "VBDI", nullable = false, length = 20)
	public String getVbdi() {
		return this.vbdi;
	}

	public void setVbdi(String vbdi) {
		this.vbdi = vbdi;
	}

	@Column(name = "NAME", nullable = false, length = 120)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "SWIFT", nullable = false, length = 20)
	public String getSwift() {
		return this.swift;
	}

	public void setSwift(String swift) {
		this.swift = swift;
	}

	@Column(name = "STREET", nullable = false, length = 120)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "STREETNUM", nullable = false, length = 40)
	public String getStreetnum() {
		return this.streetnum;
	}

	public void setStreetnum(String streetnum) {
		this.streetnum = streetnum;
	}

	@Column(name = "CITY", nullable = false, length = 120)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "ZIPCODE", nullable = false, length = 40)
	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	@Column(name = "COUNTRYCO", nullable = false, length = 10)
	public String getCountryco() {
		return this.countryco;
	}

	public void setCountryco(String countryco) {
		this.countryco = countryco;
	}

	@Column(name = "STATUS", nullable = false, precision = 2, scale = 0)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "USER", nullable = false, length = 10)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "DATETIME", nullable = false, precision = 8, scale = 0)
	public int getDatetime() {
		return this.datetime;
	}

	public void setDatetime(int datetime) {
		this.datetime = datetime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATETIMEWS", nullable = true, length = 10)
	public Date getDatetimews() {
		return this.datetimews;
	}

	public void setDatetimews(Date datetimews) {
		this.datetimews = datetimews;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "TIMEWS", length = 8)
	public Date getTimews() {
		return this.timews;
	}

	public void setTimews(Date timews) {
		this.timews = timews;
	}

	public void postaviVrijednosti(byte status, Reqmsg reqMsg, Date dateTimeWS) {
		this.status = status;
		this.reqmsg = reqMsg;
		this.datetimews = dateTimeWS;
		this.timews = dateTimeWS;
	}
}
