package hr.infomare.drrh.pojo;

// Generated 21.09.2011. 15:44:13 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Bcitemlst generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "BCITEMLST")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Bcitemlst implements java.io.Serializable {

	private int bcmsgid;
	private int bcitemid;

	private BigDecimal amount;
	private int itduedat;
	private String vendorid;
	private String fund;
	private String yearbs;
	private String funcarea;
	private String activity;
	private String buduserbs;
	private String code;
	private String yearci;
	private String descrt;
	private String type;
	private Integer refdochead;
	private String refitemnum;
	private String locationbc;
	private String user;
	private int datetime;

	public Bcitemlst() {
	}

	@Id
	@Column(name = "BCMSGID", nullable = false, precision = 9, scale = 0)
	public int getBcmsgid() {
		return this.bcmsgid;
	}

	public void setBcmsgid(int bcmsgid) {
		this.bcmsgid = bcmsgid;
	}

	@Id
	@Column(name = "BCITEMID", nullable = false, precision = 9, scale = 0)
	public int getBcitemid() {
		return this.bcitemid;
	}

	public void setBcitemid(int bcitemid) {
		this.bcitemid = bcitemid;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "ITDUEDAT", nullable = false, precision = 8, scale = 0)
	public int getItduedat() {
		return this.itduedat;
	}

	public void setItduedat(int itduedat) {
		this.itduedat = itduedat;
	}

	@Column(name = "VENDORID", nullable = false, length = 50)
	public String getVendorid() {
		return this.vendorid;
	}

	public void setVendorid(String vendorid) {
		this.vendorid = vendorid;
	}

	@Column(name = "FUND", nullable = false, length = 20)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Column(name = "YEARBS", nullable = false, length = 20)
	public String getYearbs() {
		return this.yearbs;
	}

	public void setYearbs(String yearbs) {
		this.yearbs = yearbs;
	}

	@Column(name = "FUNCAREA", nullable = false, length = 20)
	public String getFuncarea() {
		return this.funcarea;
	}

	public void setFuncarea(String funcarea) {
		this.funcarea = funcarea;
	}

	@Column(name = "BUDUSERBS", nullable = false, length = 50)
	public String getBuduserbs() {
		return buduserbs;
	}

	public void setBuduserbs(String buduserbs) {
		this.buduserbs = buduserbs;
	}

	@Column(name = "ACTIVITY", nullable = false, length = 20)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "CODE", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "YEARCI", nullable = false, length = 20)
	public String getYearci() {
		return this.yearci;
	}

	public void setYearci(String yearci) {
		this.yearci = yearci;
	}

	@Column(name = "DESCRT", nullable = false, length = 120)
	public String getDescrt() {
		return this.descrt;
	}

	public void setDescrt(String descrt) {
		this.descrt = descrt;
	}

	@Column(name = "TYPE", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "REFDOCHEAD", precision = 9, scale = 0)
	public Integer getRefdochead() {
		return this.refdochead;
	}

	public void setRefdochead(Integer refdochead) {
		this.refdochead = refdochead;
	}

	@Column(name = "REFITEMNUM", length = 20)
	public String getRefitemnum() {
		return this.refitemnum;
	}

	public void setRefitemnum(String refitemnum) {
		this.refitemnum = refitemnum;
	}

	@Column(name = "LOCATIONBC", nullable = false, length = 50)
	public String getLocationbc() {
		return this.locationbc;
	}

	public void setLocationbc(String locationbc) {
		this.locationbc = locationbc;
	}

	@Column(name = "USER", nullable = false, length = 10)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "DATETIME", nullable = false, precision = 8, scale = 0)
	public int getDatetime() {
		return this.datetime;
	}

	public void setDatetime(int datetime) {
		this.datetime = datetime;
	}

}
