package hr.infomare.drrh.pojo;

// Generated 16.06.2011. 15:40:00 by Hibernate Tools 3.2.1.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Error generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "ERROR")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Errormsg implements java.io.Serializable {

	private Long resmesid;
	private Integer errorid;
	private String target;
	private String value;
	private String errorcode;
	private String descriptio;
	private Date submdati;

	public Errormsg() {
	}

	@Id
	@Column(name = "RESMSGID", nullable = false, precision = 9, scale = 0)
	public Long getResmesid() {
		return resmesid;
	}

	public void setResmesid(Long resmesid) {
		this.resmesid = resmesid;
	}
	
	@Id
	@Column(name="ERRORID", nullable=false, precision=9, scale=0)
	public Integer getErrorid() {
		return errorid;
	}

	public void setErrorid(Integer errorid) {
		this.errorid = errorid;
	}

	@Column(name = "TARGET", nullable = true, length = 500)
	public String getTarget() {
		return this.target;
	}

	public void setTarget(String target) {
		this.target = target;
	}

	@Column(name = "VALUE", nullable = true, length = 500)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "ERRORCODE", nullable = true, length = 120)
	public String getErrorcode() {
		return this.errorcode;
	}

	public void setErrorcode(String errorcode) {
		this.errorcode = errorcode;
	}

	@Column(name = "DESCRIPTIO", nullable = true, length = 2000)
	public String getDescriptio() {
		return this.descriptio;
	}

	public void setDescriptio(String descriptio) {
		this.descriptio = descriptio;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBMDATI", nullable = false, length = 10)
	public Date getSubmdati() {
		return this.submdati;
	}

	public void setSubmdati(Date submdati) {
		this.submdati = submdati;
	}

}
