package hr.infomare.drrh.pojo;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Invitemlst generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "INVITEMLST")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Invitemlst implements java.io.Serializable {
	
	private int invmsgid;
	private long invitemid;

	
	private BigDecimal amountini;
	private String descinvit;
	private String fund;
	private String yearbs;
	private String funcarea;
	private String activity;
	private String code;
	private String yearci;
	private String descrt;
	private String type;
	private String glaccount;
	private BigDecimal qty;
	private String qtyunit;
	private Integer refdocid;
	private Long lineitnum;
	private String location;
	private BigDecimal lcuramou;
	private String debcreind;
	private String user;
	private int datetime;

	public Invitemlst() {
	}

	@Id
	@Column(name = "INVMSGID", nullable = false, precision = 9, scale = 0)
	public int getInvmsgid() {
		return this.invmsgid;
	}

	public void setInvmsgid(int invmsgid) {
		this.invmsgid = invmsgid;
	}

	@Id
	@Column(name = "INVITEMID", nullable = false, precision = 9, scale = 0)
	public long getInvitemid() {
		return this.invitemid;
	}

	public void setInvitemid(long invitemid) {
		this.invitemid = invitemid;
	}
	
	@Column(name = "REFDOCID", precision = 9, scale = 0)
	public Integer getRefdochead() {
		return this.refdocid;
	}

	public void setRefdochead(Integer refdocid) {
		this.refdocid = refdocid;
	}	

	@Column(name = "AMOUNTINI", nullable = false, precision = 15)
	public BigDecimal getAmountini() {
		return this.amountini;
	}

	public void setAmountini(BigDecimal amountini) {
		this.amountini = amountini;
	}

	@Column(name = "DESCINVIT", nullable = false, length = 120)
	public String getDescinvit() {
		return this.descinvit;
	}

	public void setDescinvit(String descinvit) {
		this.descinvit = descinvit;
	}

	@Column(name = "FUND", nullable = false, length = 20)
	public String getFund() {
		return this.fund;
	}

	public void setFund(String fund) {
		this.fund = fund;
	}

	@Column(name = "YEARBS", nullable = false, length = 20)
	public String getYearbs() {
		return this.yearbs;
	}

	public void setYearbs(String yearbs) {
		this.yearbs = yearbs;
	}

	@Column(name = "FUNCAREA", nullable = false, length = 20)
	public String getFuncarea() {
		return this.funcarea;
	}

	public void setFuncarea(String funcarea) {
		this.funcarea = funcarea;
	}

	@Column(name = "ACTIVITY", nullable = false, length = 20)
	public String getActivity() {
		return this.activity;
	}

	public void setActivity(String activity) {
		this.activity = activity;
	}

	@Column(name = "CODE", nullable = false, length = 50)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "YEARCI", nullable = false, length = 20)
	public String getYearci() {
		return this.yearci;
	}

	public void setYearci(String yearci) {
		this.yearci = yearci;
	}

	@Column(name = "DESCRT", nullable = false, length = 120)
	public String getDescrt() {
		return this.descrt;
	}

	public void setDescrt(String descrt) {
		this.descrt = descrt;
	}

	@Column(name = "TYPE", length = 20)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "GLACCOUNT", nullable = false, length = 15)
	public String getGlaccount() {
		return this.glaccount;
	}

	public void setGlaccount(String glaccount) {
		this.glaccount = glaccount;
	}

	@Column(name = "QTY", precision = 10)
	public BigDecimal getQty() {
		return this.qty;
	}

	public void setQty(BigDecimal qty) {
		this.qty = qty;
	}

	@Column(name = "QTYUNIT", length = 25)
	public String getQtyunit() {
		return this.qtyunit;
	}

	public void setQtyunit(String qtyunit) {
		this.qtyunit = qtyunit;
	}

	@Column(name = "LINEITNUM", precision = 9, scale = 0)
	public Long getLineitnum() {
		return this.lineitnum;
	}

	public void setLineitnum(Long lineitnum) {
		this.lineitnum = lineitnum;
	}

	@Column(name = "LOCATION", length = 50)
	public String getLocation() {
		return this.location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	@Column(name = "LCURAMOU", nullable = false, precision = 15)
	public BigDecimal getLcuramou() {
		return this.lcuramou;
	}

	public void setLcuramou(BigDecimal lcuramou) {
		this.lcuramou = lcuramou;
	}

	@Column(name = "DEBCREIND", nullable = false, length = 1)
	public String getDebcreind() {
		return this.debcreind;
	}

	public void setDebcreind(String debcreind) {
		this.debcreind = debcreind;
	}

	@Column(name = "USER", nullable = false, length = 10)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "DATETIME", nullable = false, precision = 8, scale = 0)
	public int getDatetime() {
		return this.datetime;
	}

	public void setDatetime(int datetime) {
		this.datetime = datetime;
	}

}
