package hr.infomare.drrh.pojo;

// Generated 08.12.2011. 12:34:10 by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Payexec generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "PAYEXEC"

)
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Payexec implements java.io.Serializable {

	private int bufmisdoc;
	private Integer dochead;
	private String sapdocid;
	private String bufmisven;
	private BigDecimal amount;
	private BigDecimal invlcam;
	private String payref;
	private String paydesc;
	private String payecstty;
	private int paydate;
	private String iscess;
	private Integer resmsgid;
	private Date datetimews;

	public Payexec() {
	}

	@Id
	@Column(name = "BUFMISDOC", unique = true, nullable = false, precision = 9, scale = 0)
	public int getBufmisdoc() {
		return this.bufmisdoc;
	}

	public void setBufmisdoc(int bufmisdoc) {
		this.bufmisdoc = bufmisdoc;
	}
	
	@Column(name = "REFDOCID", precision = 9, scale = 0)
	public Integer getDochead() {
		return this.dochead;
	}

	public void setDochead(Integer dochead) {
		this.dochead = dochead;
	}

	@Column(name = "SAPDOCID", nullable = false, length = 50)
	public String getSapdocid() {
		return this.sapdocid;
	}

	public void setSapdocid(String sapdocid) {
		this.sapdocid = sapdocid;
	}

	@Column(name = "BUFMISVEN", nullable = false, length = 7)
	public String getBufmisven() {
		return this.bufmisven;
	}

	public void setBufmisven(String bufmisven) {
		this.bufmisven = bufmisven;
	}

	@Column(name = "AMOUNT", nullable = false, precision = 15)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "INVLCAM", nullable = false, precision = 15)
	public BigDecimal getInvlcam() {
		return this.invlcam;
	}

	public void setInvlcam(BigDecimal invlcam) {
		this.invlcam = invlcam;
	}

	@Column(name = "PAYREF", nullable = false, length = 50)
	public String getPayref() {
		return this.payref;
	}

	public void setPayref(String payref) {
		this.payref = payref;
	}

	@Column(name = "PAYDESC", nullable = false, length = 120)
	public String getPaydesc() {
		return this.paydesc;
	}

	public void setPaydesc(String paydesc) {
		this.paydesc = paydesc;
	}

	@Column(name = "PAYECSTTY", nullable = false, length = 50)
	public String getPayecstty() {
		return this.payecstty;
	}

	public void setPayecstty(String payecstty) {
		this.payecstty = payecstty;
	}

	@Column(name = "PAYDATE", nullable = false, precision = 8, scale = 0)
	public int getPaydate() {
		return this.paydate;
	}

	public void setPaydate(int paydate) {
		this.paydate = paydate;
	}

	@Column(name = "ISCESS", nullable = false, length = 1)
	public String getIscess() {
		return this.iscess;
	}

	public void setIscess(String iscess) {
		this.iscess = iscess;
	}

	@Column(name = "RESMSGID", precision = 9, scale = 0)
	public Integer getResmsgid() {
		return this.resmsgid;
	}

	public void setResmsgid(Integer resmsgid) {
		this.resmsgid = resmsgid;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATETIMEWS", length = 10)
	public Date getDatetimews() {
		return this.datetimews;
	}

	public void setDatetimews(Date datetimews) {
		this.datetimews = datetimews;
	}

}
