package hr.infomare.drrh.pojo;

// Generated 16.06.2011. 15:40:00 by Hibernate Tools 3.2.1.GA

import hr.infomare.drrh.pomocni.PomocnaDatum;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import budgetuserlibrary.gw.fmis.ibm.hr.infotypes.MessageHeader;

/**
 * Reqmsg generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "REQMSG")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Reqmsg implements java.io.Serializable {

	private Integer reqmsgid;
	private Long resmsgid;
	private String msgname;
	private Date submdati;
	private Long eventlid;

	public Reqmsg() {
	}

	@Id
	@Column(name = "REQMSGID", unique = true, nullable = false, precision = 9, scale = 0)
	public Integer getReqmsgid() {
		return this.reqmsgid;
	}

	public void setReqmsgid(Integer reqmsgid) {
		this.reqmsgid = reqmsgid;
	}

	@Column(name = "RESMSGID", nullable = true, precision = 9, scale = 0)
	public Long getResmsg() {
		return this.resmsgid;
	}

	public void setResmsg(Long resmsgid) {
		this.resmsgid = resmsgid;
	}

	@Column(name = "MSGNAME", nullable = false, length = 120)
	public String getMsgname() {
		return this.msgname;
	}

	public void setMsgname(String msgname) {
		this.msgname = msgname;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "SUBMDATI", nullable = false, length = 10)
	public Date getSubmdati() {
		return this.submdati;
	}

	public void setSubmdati(Date submdati) {
		this.submdati = submdati;
	}

	@Column(name = "EVENTLID", nullable = true, precision = 9, scale = 0)
	public Long getEventlid() {
		return this.eventlid;
	}

	public void setEventlid(Long eventlid) {
		this.eventlid = eventlid;
	}

	public void postaviVrijednosti(MessageHeader messageHeader,
			Integer reqmsgid, String msgname) {
		this.reqmsgid = reqmsgid;
		this.resmsgid = messageHeader.getResponseMsgId();
		this.msgname = msgname;
		this.submdati = PomocnaDatum.XMLDatumUDate(messageHeader
				.getSubmitionTimestamp());
		this.eventlid = messageHeader.getEventId();

	}

	public void postaviVrijednosti(MessageHeader messageHeader) {
		this.resmsgid = messageHeader.getResponseMsgId();
	}
}