package hr.infomare.drrh.pojo;

// Generated 21.02.2012. 16:03:52 by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Retrive generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "RETRIVE")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Retrive implements java.io.Serializable {

	private int zero;
	private Integer idVendor;
	private Integer idVenbank;
	private Integer idUgovor;
	private Integer idNarudz;
	private Integer idNajava;
	private Integer idInvoice;
	private Integer idPayexec;

	public Retrive() {
	}

	@Id
	@Column(name = "ZERO", unique = true, nullable = false, precision = 1, scale = 0)
	public int getZero() {
		return this.zero;
	}

	public void setZero(int zero) {
		this.zero = zero;
	}

	@Column(name = "ID_VENDOR", precision = 9, scale = 0)
	public Integer getIdVendor() {
		return this.idVendor;
	}

	public void setIdVendor(Integer idVendor) {
		this.idVendor = idVendor;
	}

	@Column(name = "ID_VENBANK", precision = 9, scale = 0)
	public Integer getIdVenbank() {
		return this.idVenbank;
	}

	public void setIdVenbank(Integer idVenbank) {
		this.idVenbank = idVenbank;
	}

	@Column(name = "ID_UGOVOR", precision = 9, scale = 0)
	public Integer getIdUgovor() {
		return this.idUgovor;
	}

	public void setIdUgovor(Integer idUgovor) {
		this.idUgovor = idUgovor;
	}

	@Column(name = "ID_NARUDZ", precision = 9, scale = 0)
	public Integer getIdNarudz() {
		return this.idNarudz;
	}

	public void setIdNarudz(Integer idNarudz) {
		this.idNarudz = idNarudz;
	}

	@Column(name = "ID_NAJAVA", precision = 9, scale = 0)
	public Integer getIdNajava() {
		return this.idNajava;
	}

	public void setIdNajava(Integer idNajava) {
		this.idNajava = idNajava;
	}

	@Column(name = "ID_INVOICE", precision = 9, scale = 0)
	public Integer getIdInvoice() {
		return this.idInvoice;
	}

	public void setIdInvoice(Integer idInvoice) {
		this.idInvoice = idInvoice;
	}

	@Column(name = "ID_PAYEXEC", precision = 9, scale = 0)
	public Integer getIdPayexec() {
		return this.idPayexec;
	}

	public void setIdPayexec(Integer idPayexec) {
		this.idPayexec = idPayexec;
	}

}