package hr.infomare.drrh.pojo;

// Generated 16.06.2011. 15:40:00 by Hibernate Tools 3.2.1.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Venbanaccm generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "VENBANACCM")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Venbanaccm implements java.io.Serializable {

	private int idVebaacm;
	private Reqmsg reqmsg;
	private int f46ctr;
	private String f46f41;
	private byte opt;
	private String vbdi;
	private String iban;
	private String swift;
	private String venbanacc;
	private String venbancou;
	private String reference;
	private String sapbanktyp;
	private String accountnam;
	private int validto;
	private byte status;
	private String user;
	private int datetime;
	private Date datetimews;

	public Venbanaccm() {
	}

	@Id
	@Column(name = "ID_VEBAACM", unique = true, nullable = false, precision = 9, scale = 0)
	public int getIdVebaacm() {
		return this.idVebaacm;
	}

	public void setIdVebaacm(int idVebaacm) {
		this.idVebaacm = idVebaacm;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "REQMSGID")
	public Reqmsg getReqmsg() {
		return this.reqmsg;
	}

	public void setReqmsg(Reqmsg reqmsg) {
		this.reqmsg = reqmsg;
	}

	@Column(name = "F46CTR", nullable = false, precision = 7, scale = 0)
	public int getF46ctr() {
		return this.f46ctr;
	}

	public void setF46ctr(int f46ctr) {
		this.f46ctr = f46ctr;
	}

	@Column(name = "F46F41", nullable = false, length = 7)
	public String getF46f41() {
		return f46f41;
	}

	public void setF46f41(String f46f41) {
		this.f46f41 = f46f41;
	}

	@Column(name = "OPT", nullable = false, precision = 2, scale = 0)
	public byte getOpt() {
		return this.opt;
	}

	public void setOpt(byte opt) {
		this.opt = opt;
	}

	@Column(name = "VBDI", nullable = false, length = 20)
	public String getVbdi() {
		return this.vbdi;
	}

	public void setVbdi(String vbdi) {
		this.vbdi = vbdi;
	}

	@Column(name = "IBAN", nullable = false, length = 50)
	public String getIban() {
		return this.iban;
	}

	public void setIban(String iban) {
		this.iban = iban;
	}

	@Column(name = "SWIFT", nullable = false, length = 20)
	public String getSwift() {
		return this.swift;
	}

	public void setSwift(String swift) {
		this.swift = swift;
	}

	@Column(name = "VENBANACC", nullable = false, length = 50)
	public String getVenbanacc() {
		return this.venbanacc;
	}

	public void setVenbanacc(String venbanacc) {
		this.venbanacc = venbanacc;
	}

	@Column(name = "VENBANCOU", nullable = false, length = 10)
	public String getVenbancou() {
		return this.venbancou;
	}

	public void setVenbancou(String venbancou) {
		this.venbancou = venbancou;
	}

	@Column(name = "REFERENCE", nullable = false, length = 40)
	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	@Column(name = "SAPBANKTYP", nullable = false, length = 40)
	public String getSapbanktyp() {
		return this.sapbanktyp;
	}

	public void setSapbanktyp(String sapbanktyp) {
		this.sapbanktyp = sapbanktyp;
	}

	@Column(name = "ACCOUNTNAM", nullable = false, length = 120)
	public String getAccountnam() {
		return this.accountnam;
	}

	public void setAccountnam(String accountnam) {
		this.accountnam = accountnam;
	}

	@Column(name = "VALIDTO", nullable = false, precision = 8, scale = 0)
	public int getValidto() {
		return this.validto;
	}

	public void setValidto(int validto) {
		this.validto = validto;
	}

	@Column(name = "STATUS", nullable = false, precision = 2, scale = 0)
	public byte getStatus() {
		return this.status;
	}

	public void setStatus(byte status) {
		this.status = status;
	}

	@Column(name = "USER", nullable = false, length = 10)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "DATETIME", nullable = false, precision = 8, scale = 0)
	public int getDatetime() {
		return this.datetime;
	}

	public void setDatetime(int datetime) {
		this.datetime = datetime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATETIMEWS", length = 10)
	public Date getDatetimews() {
		return this.datetimews;
	}

	public void setDatetimews(Date datetimews) {
		this.datetimews = datetimews;
	}

	public void postaviVrijednosti(byte status, Reqmsg reqMsg, Date dateTimeWS) {
		this.status = status;
		this.reqmsg = reqMsg;
		this.datetimews = dateTimeWS;

	}
}
