/*
 * 
 */

package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.binding2;

import hr.infomare.drrh.pomocni.Log;
import hr.infomare.drrh.pomocni.PomocnaError;
import hr.infomare.drrh.pomocni.PomocnaWSDL;
import hr.infomare.drrh.postavke.Postavke;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0 2011-12-05T12:37:57.144+01:00
 * Generated source version: 2.4.0
 * 
 */

@WebServiceClient(name = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpService", wsdlLocation = "http://localhost:8080/Infomare_drrh_web_services/services/ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort?wsdl", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/Binding2")
public class ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService
		extends Service {
	public static String TARGET_NAMESPACE;
	public static String SERVIS;
	public static String PORT;

	public static URL WSDL_LOCATION;

	public static QName SERVICE;
	public static QName responseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort;
	static {
		PomocnaWSDL.locirajWebServis(Postavke.WSDL_RESPONSE);
		TARGET_NAMESPACE = PomocnaWSDL.TARGET_NAMESPACE;
		SERVIS = PomocnaWSDL.SERVIS;
		PORT = PomocnaWSDL.PORT;

		SERVICE = new QName(TARGET_NAMESPACE, SERVIS);
		responseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort = new QName(
				TARGET_NAMESPACE, PORT);
		URL url = null;
		try {
			url = new URL(Postavke.WSDL_CONTRACT);
		} catch (MalformedURLException e) {
			Log.loger.severe(PomocnaError.getErrorMessage(e));
		}
		WSDL_LOCATION = url;
	}

	public ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService(
			URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService(
			URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns ResponseMessageHandlerService
	 */
	@WebEndpoint(name = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort")
	public ResponseMessageHandlerService getResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort() {
		return super
				.getPort(
						responseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort,
						ResponseMessageHandlerService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ResponseMessageHandlerService
	 */
	@WebEndpoint(name = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort")
	public ResponseMessageHandlerService getResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort(
			WebServiceFeature... features) {
		return super
				.getPort(
						responseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort,
						ResponseMessageHandlerService.class, features);
	}

}
