
/*
 * 
 */

package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.binding2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import budgetuserlibrary.gw.fmis.ibm.hr.interfaces.responsemessagehandlerservice.ResponseMessageHandlerService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-12-05T12:37:57.144+01:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpService", 
                  wsdlLocation = "http://localhost:8080/Infomare_drrh_web_services/services/ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort?wsdl",
                  targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/Binding2") 
public class ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/Binding2", "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpService");
    public final static QName ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort = new QName("http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ResponseMessageHandlerService/Binding2", "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/Infomare_drrh_web_services/services/ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Infomare_drrh_web_services/services/ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns ResponseMessageHandlerService
     */
    @WebEndpoint(name = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort")
    public ResponseMessageHandlerService getResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort() {
        return super.getPort(ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort, ResponseMessageHandlerService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ResponseMessageHandlerService
     */
    @WebEndpoint(name = "ResponseMessageHandlerServiceExport_ResponseMessageHandlerServiceHttpPort")
    public ResponseMessageHandlerService getResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort(WebServiceFeature... features) {
        return super.getPort(ResponseMessageHandlerServiceExportResponseMessageHandlerServiceHttpPort, ResponseMessageHandlerService.class, features);
    }

}
