package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2011-10-05T09:15:48.596+02:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", name = "ReservationManagementService")
@XmlSeeAlso({ObjectFactory.class, budgetuserlibrary.gw.fmis.ibm.hr.infotypes.ObjectFactory.class, budgetuserlibrary.gw.fmis.ibm.hr.messages.ObjectFactory.class, bufmisbudgetexecution.gw.fmis.ibm.hr.infotypes.ObjectFactory.class})
public interface ReservationManagementService {

    @WebResult(name = "changeReservationParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "changeReservation", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.ChangeReservation")
    @WebMethod
    @ResponseWrapper(localName = "changeReservationResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.ChangeReservationResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.ReservationResponseMsg changeReservation(
        @WebParam(name = "changeReservationParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.ReservationChangeRequestMsg changeReservationParamIn
    );

    @WebResult(name = "closeReservationParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "closeReservation", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.CloseReservation")
    @WebMethod
    @ResponseWrapper(localName = "closeReservationResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.CloseReservationResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.ReservationResponseMsg closeReservation(
        @WebParam(name = "closeReservationParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.ReservationCloseRequestMsg closeReservationParamIn
    );

    @WebResult(name = "createReservationParamReturn", targetNamespace = "")
    @RequestWrapper(localName = "createReservation", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.CreateReservation")
    @WebMethod
    @ResponseWrapper(localName = "createReservationResponse", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ReservationManagementService/", className = "budgetuserlibrary.gw.fmis.ibm.hr.interfaces.reservationmanagementservice.CreateReservationResponse")
    public budgetuserlibrary.gw.fmis.ibm.hr.messages.ReservationResponseMsg createReservation(
        @WebParam(name = "createReservationParamIn", targetNamespace = "")
        budgetuserlibrary.gw.fmis.ibm.hr.messages.ReservationCreateRequestMsg createReservationParamIn
    );
}
