package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.binding;

import hr.infomare.drrh.pomocni.Log;
import hr.infomare.drrh.pomocni.PomocnaError;
import hr.infomare.drrh.pomocni.PomocnaWSDL;
import hr.infomare.drrh.postavke.Postavke;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import budgetuserlibrary.gw.fmis.ibm.hr.interfaces.bankmanagementinterface.BankManagementInterface;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0 2011-06-20T14:40:23.944+02:00
 * Generated source version: 2.4.0
 * 
 */

@WebServiceClient(name = "BankManagementInterfaceExport_BankManagementInterfaceHttpService", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/BankManagementInterface/Binding")
public class BankManagementInterfaceExportBankManagementInterfaceHttpService
		extends Service {
	public static String TARGET_NAMESPACE;
	public static String SERVIS;
	public static String PORT;

	public static URL WSDL_LOCATION;
	public static QName SERVICE;
	public static QName BankManagementInterfaceExportBankManagementInterfaceHttpPort;
	static {
		PomocnaWSDL.locirajWebServis(Postavke.WSDL_BANK);
		TARGET_NAMESPACE = PomocnaWSDL.TARGET_NAMESPACE;
		SERVIS = PomocnaWSDL.SERVIS;
		PORT = PomocnaWSDL.PORT;
		
		SERVICE = new QName(TARGET_NAMESPACE, SERVIS);
		BankManagementInterfaceExportBankManagementInterfaceHttpPort = new QName(
				TARGET_NAMESPACE, PORT);
		URL url = null;
		try {
			url = new URL(Postavke.WSDL_BANK);
		} catch (MalformedURLException e) {
			Log.loger.severe(PomocnaError.getErrorMessage(e));
		}
		WSDL_LOCATION = url;
	}

	public BankManagementInterfaceExportBankManagementInterfaceHttpService(
			URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public BankManagementInterfaceExportBankManagementInterfaceHttpService(
			URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BankManagementInterfaceExportBankManagementInterfaceHttpService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns BankManagementInterface
	 */
	@WebEndpoint(name = "BankManagementInterfaceExport_BankManagementInterfaceHttpPort")
	public BankManagementInterface getBankManagementInterfaceExportBankManagementInterfaceHttpPort() {
		return super.getPort(
				BankManagementInterfaceExportBankManagementInterfaceHttpPort,
				BankManagementInterface.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns BankManagementInterface
	 */
	@WebEndpoint(name = "BankManagementInterfaceExport_BankManagementInterfaceHttpPort")
	public BankManagementInterface getBankManagementInterfaceExportBankManagementInterfaceHttpPort(
			WebServiceFeature... features) {
		return super.getPort(
				BankManagementInterfaceExportBankManagementInterfaceHttpPort,
				BankManagementInterface.class, features);
	}

}
