package budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.binding;

import hr.infomare.drrh.pomocni.Log;
import hr.infomare.drrh.pomocni.PomocnaError;
import hr.infomare.drrh.pomocni.PomocnaWSDL;
import hr.infomare.drrh.postavke.Postavke;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import budgetuserlibrary.gw.fmis.ibm.hr.interfaces.contractmanagementservice.ContractManagementService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0 2011-10-14T14:54:55.470+02:00
 * Generated source version: 2.4.0
 * 
 */

@WebServiceClient(name = "manageContractExport_ContractManagementServiceHttpService", wsdlLocation = "http://wad.infomare.hr:8080/Infomare_drrh_web_services/services/manageContractExport_ContractManagementServiceHttpPort?wsdl", targetNamespace = "http://hr.ibm.fmis.gw.BudgetUserLibrary/interfaces/ContractManagementService/Binding")
public class ManageContractExportContractManagementServiceHttpService extends
		Service {
	public static String TARGET_NAMESPACE;
	public static String SERVIS;
	public static String PORT;

	public static URL WSDL_LOCATION;

	public static QName SERVICE;
	public static QName manageContractExportContractManagementServiceHttpPort;
	static {
		PomocnaWSDL.locirajWebServis(Postavke.WSDL_CONTRACT);
		TARGET_NAMESPACE = PomocnaWSDL.TARGET_NAMESPACE;
		SERVIS = PomocnaWSDL.SERVIS;
		PORT = PomocnaWSDL.PORT;

		SERVICE = new QName(TARGET_NAMESPACE, SERVIS);
		manageContractExportContractManagementServiceHttpPort = new QName(
				TARGET_NAMESPACE, PORT);
		URL url = null;
		try {
			url = new URL(Postavke.WSDL_CONTRACT);
		} catch (MalformedURLException e) {
			Log.loger.severe(PomocnaError.getErrorMessage(e));
		}
		WSDL_LOCATION = url;
	}

	public ManageContractExportContractManagementServiceHttpService(
			URL wsdlLocation) {
		super(wsdlLocation, SERVICE);
	}

	public ManageContractExportContractManagementServiceHttpService(
			URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ManageContractExportContractManagementServiceHttpService() {
		super(WSDL_LOCATION, SERVICE);
	}

	/**
	 * 
	 * @return returns ContractManagementService
	 */
	@WebEndpoint(name = "manageContractExport_ContractManagementServiceHttpPort")
	public ContractManagementService getManageContractExportContractManagementServiceHttpPort() {
		return super.getPort(
				manageContractExportContractManagementServiceHttpPort,
				ContractManagementService.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns ContractManagementService
	 */
	@WebEndpoint(name = "manageContractExport_ContractManagementServiceHttpPort")
	public ContractManagementService getManageContractExportContractManagementServiceHttpPort(
			WebServiceFeature... features) {
		return super.getPort(
				manageContractExportContractManagementServiceHttpPort,
				ContractManagementService.class, features);
	}

}
